Update README.md
Vulwsztyn/iban-examples pull request #1
Opened 2022-10-02 16:22 UTC by Gyshie

Updated the readme file

2022-10-02 17:39 UTC, Vulwsztyn commented on README.md
> +IBAN stands for International Bank Account Number and is an internationally accepted numbering system that identifies individual bank accounts worldwide. Banks use IBANs to process money transfers an
Remove this please

2022-10-02 17:41 UTC, Vulwsztyn requested changes

2022-10-02 17:41 UTC, Vulwsztyn commented on README.md
> +IBAN stands for International Bank Account Number and is an internationally accepted numbering system that identifies individual bank accounts worldwide. Banks use IBANs to process money transfers an
.

2022-10-03 12:31 UTC, Vulwsztyn commented on README.md
> +IBAN stands for International Bank Account Number and is an internationally accepted numbering system that identifies individual bank accounts worldwide. Banks use IBANs to process money transfers an
ping

2022-10-03 12:42 UTC, Gyshie commented
Hello @Vulwsztyn you want me to remove my suggestion or what? I didn't get you. Can you please classify it?

2022-10-03 12:43 UTC, Vulwsztyn commented
> Hello @Vulwsztyn you want me to remove my suggestion or what? I didn't get you. Can you please classify it?

Yeah, sorry. I want you to remove last line of text from readme. It is not the aim of this repo to tell people what IBAN is. I'm sorry for inconvenience and thankful for your contribution.

2022-10-03 12:50 UTC, Gyshie commented
# IBAN Examples

This repository consists of examples of IBANs.

Feel free to contribute by adding Valid IBAN examples to the file for the appropriate country. 🤍

2022-10-03 12:50 UTC, closed without merging

2022-10-03 12:52 UTC, Gyshie commented
Like above?

2022-10-03 16:26 UTC, Vulwsztyn commented
> Like above?

Yes.

Why did you close this PR? You could have added a new commit removing the line.

Are you going to commit the IBAN examples you added in this PR in a new PR?

2022-10-03 17:39 UTC, Gyshie commented
Hope you got the new PR :)

2022-10-03 21:31 UTC, Vulwsztyn commented
> Hope you got the new PR :)
Only the one with readme changes not the ones with cw and ky IBANs

2022-10-04 00:14 UTC, Gyshie commented
Oh! I'll resend em. Sry

2022-10-04 00:19 UTC, Gyshie commented
I made it as a new PR.